%% triangle equi
ll = 0.01*3;
hh = sqrt(ll^2 - (.5*ll)^2);
O_features = [ ...
    [ -ll/2; -hh/2;  0], ...
    [ ll/2; -hh/2; 0 ], ...
    [ 0; hh/2; 0], ...
    ];
bari = sum(O_features,2)/size(O_features,2);
O_T_C_desired = SE3(rotx(0), bari' + [0 0 .05]);

C_features_desired = homtrans(inv(O_T_C_desired),O_features);