function DV = buildFunDV_lambdaT(ek,s_star,Ds_stark,forward_action_enabled)

if(nargin < 4 || isempty(forward_action_enabled))
    forward_action_enabled = true;
end
if(nargin < 3 || isempty(Ds_stark))
    Ds_stark = 0;
    forward_action_enabled = false;
end

s = ek+s_star;
L = computeL(s);
Lpinv = pinv(L);

% f_ekp1 = @(lambda)discreteErrorSystemClosedLoop_internal_lambda(...
%     lambda,...
%     ek,...
%     Ts,...
%     L,...
%     Lpinv,...
%     Ds_stark, ...
%     forward_action_enabled);
f_ekp1 = @(lambdaT)discreteErrorSystemClosedLoop_internal( ...
    lambdaT, ...
    ek, ...
    L, ...
    Lpinv, ...
    Ds_stark, ...
    forward_action_enabled ...
    );

norm_ek_2 = norm(ek)^2;
DV = @(lambdaT) norm(f_ekp1(lambdaT))^2 - norm_ek_2;

end

